# Użycie obrazu bazowego z Pythonem
FROM python:3.9-slim

# Ustawienia środowiska
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Instalacja zależności systemowych
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Ustawienie katalogu roboczego
WORKDIR /app

# Instalacja zależności Pythona
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Skopiowanie kodu aplikacji
COPY . /app/

# Uruchomienie serwera Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
